import { Agent } from "./types";

const mockTimestamp = { seconds: Math.floor(Date.now() / 1000), nanoseconds: 0 };

export const MOCK_AGENTS: Agent[] = [
  {
    id: "mock-code-reviewer-1",
    name: "AutoPR Reviewer Pro",
    description: "Deep codebase analysis using Claude 3.5 Sonnet to automatically review Pull Requests and suggest performant refactors.",
    creatorId: "mock-user-1",
    creatorUsername: "ai_ninja",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-code-reviewer-1",
    capabilityTags: ["code-review", "testing", "security"],
    supportedLanguages: ["typescript", "python", "go", "Rust"],
    latencyMs: 1200,
    costPerCall: 0.15,
    inputSchema: { type: "object", properties: { repoUrl: { type: "string" }, prNumber: { type: "number" } } },
    outputSchema: { type: "object", properties: { approved: { type: "boolean" }, reviewComments: { type: "array" } } },
    exampleInput: { repoUrl: "https://github.com/user/repo", prNumber: 42 },
    exampleOutput: { approved: true, reviewComments: ["Great code!", "Consider memoizing this component"] },
    version: "1.2.0",
    status: "active",
    trustScore: 98,
    totalCalls: 45200,
    avgLatencyMs: 1100,
    uptimePercent: 99.9,
    rating: 4.8,
    reviewCount: 156,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 100
  },
  {
    id: "mock-data-extractor-2",
    name: "Legal Doc Parser",
    description: "Extracts key clauses, dates, and obligations from dense legal PDFs with 99.9% accuracy. Perfect for contract analysis.",
    creatorId: "mock-user-2",
    creatorUsername: "legalTechCorp",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-data-extractor-2",
    capabilityTags: ["data-extraction", "legal", "summarization"],
    supportedLanguages: ["python", "node"],
    latencyMs: 3500,
    costPerCall: 0.50,
    inputSchema: { type: "object", properties: { documentBase64: { type: "string" } } },
    outputSchema: { type: "object", properties: { parties: { type: "array" }, dates: { type: "array" }, summary: { type: "string" } } },
    exampleInput: { documentBase64: "JVBERi0xLjQK..." },
    exampleOutput: { parties: ["Company A", "Company B"], dates: ["2026-01-01"], summary: "Standard NDA" },
    version: "2.0.1",
    status: "active",
    trustScore: 95,
    totalCalls: 120500,
    avgLatencyMs: 3400,
    uptimePercent: 99.5,
    rating: 4.9,
    reviewCount: 342,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 50
  },
  {
    id: "mock-sql-generator-3",
    name: "Text2SQL Engine",
    description: "Translate natural language to complex Postgres queries instantly. Understands database schemas automatically.",
    creatorId: "mock-user-3",
    creatorUsername: "db_master",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-sql-generator-3",
    capabilityTags: ["generative", "database", "productivity"],
    supportedLanguages: ["ruby", "php", "go", "node"],
    latencyMs: 800,
    costPerCall: 0.05,
    inputSchema: { type: "object", properties: { prompt: { type: "string" }, schema: { type: "string" } } },
    outputSchema: { type: "object", properties: { sql: { type: "string" } } },
    exampleInput: { prompt: "Find users with more than 5 purchases last month", schema: "CREATE TABLE users..." },
    exampleOutput: { sql: "SELECT * FROM users JOIN purchases ON..." },
    version: "0.9.5",
    status: "active",
    trustScore: 88,
    totalCalls: 8500,
    avgLatencyMs: 850,
    uptimePercent: 98.0,
    rating: 4.5,
    reviewCount: 45,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 200
  },
  {
    id: "mock-customer-support-4",
    name: "CX Resolver Bot",
    description: "Autonomous customer support agent that resolves 80% of L1 support tickets. Integrates directly with Zendesk and Intercom.",
    creatorId: "mock-user-4",
    creatorUsername: "support_heroes",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-customer-support-4",
    capabilityTags: ["nlp", "customer-support", "automation"],
    supportedLanguages: ["javascript", "python"],
    latencyMs: 1500,
    costPerCall: 0.20,
    inputSchema: { type: "object", properties: { userMessage: { type: "string" }, history: { type: "array" } } },
    outputSchema: { type: "object", properties: { reply: { type: "string" }, resolved: { type: "boolean" } } },
    exampleInput: { userMessage: "How do I reset my password?", history: [] },
    exampleOutput: { reply: "You can reset your password by visiting the settings page.", resolved: true },
    version: "3.1.0",
    status: "active",
    trustScore: 92,
    totalCalls: 540000,
    avgLatencyMs: 1600,
    uptimePercent: 99.9,
    rating: 4.7,
    reviewCount: 890,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 300
  },
  {
    id: "mock-medical-vision-5",
    name: "X-Ray Vision AI",
    description: "Specialized computer vision model for analyzing medical X-Rays and MRIs to highlight potential anomalies with high precision.",
    creatorId: "mock-user-5",
    creatorUsername: "healthtech_ai",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-medical-vision-5",
    capabilityTags: ["computer-vision", "healthcare", "analysis"],
    supportedLanguages: ["python", "c++"],
    latencyMs: 4500,
    costPerCall: 1.50,
    inputSchema: { type: "object", properties: { imageBase64: { type: "string" } } },
    outputSchema: { type: "object", properties: { anomaliesDetected: { type: "boolean" }, confidence: { type: "number" } } },
    exampleInput: { imageBase64: "iVBORw0KGgo..." },
    exampleOutput: { anomaliesDetected: false, confidence: 0.98 },
    version: "1.0.5",
    status: "active",
    trustScore: 99,
    totalCalls: 12500,
    avgLatencyMs: 4200,
    uptimePercent: 99.99,
    rating: 4.9,
    reviewCount: 112,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 20
  },
  {
    id: "mock-marketing-copy-6",
    name: "Growth Hacker AI",
    description: "Generates high-converting ad copy, viral tweets, and SEO-optimized blog posts based on trending keywords.",
    creatorId: "mock-user-6",
    creatorUsername: "growth_god",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-marketing-copy-6",
    capabilityTags: ["content-creation", "marketing", "generative"],
    supportedLanguages: ["javascript", "php"],
    latencyMs: 1100,
    costPerCall: 0.10,
    inputSchema: { type: "object", properties: { topic: { type: "string" }, platform: { type: "string" } } },
    outputSchema: { type: "object", properties: { copy: { type: "array" } } },
    exampleInput: { topic: "New AI product launch", platform: "twitter" },
    exampleOutput: { copy: ["Just launched the most powerful AI tool! 🚀 #AI #Tech"] },
    version: "2.4.0",
    status: "active",
    trustScore: 85,
    totalCalls: 89000,
    avgLatencyMs: 1150,
    uptimePercent: 98.5,
    rating: 4.4,
    reviewCount: 304,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 150
  },
  {
    id: "mock-ppt-summarizer-6b",
    name: "DeckBrief AI",
    description: "Summarizes PowerPoint decks, lecture slides, and pitch presentations into clean notes, study guides, and speaker talking points.",
    creatorId: "mock-user-6b",
    creatorUsername: "slidesmith",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-ppt-summarizer-6b",
    capabilityTags: ["summarization", "presentation", "content-creation"],
    supportedLanguages: ["python", "typescript", "javascript"],
    latencyMs: 1400,
    costPerCall: 0.09,
    inputSchema: { type: "object", properties: { fileUrl: { type: "string" }, outputMode: { type: "string" } } },
    outputSchema: { type: "object", properties: { summary: { type: "string" }, bulletPoints: { type: "array" }, speakerNotes: { type: "array" } } },
    exampleInput: { fileUrl: "https://example.com/deck.pptx", outputMode: "study-notes" },
    exampleOutput: { summary: "Quarterly growth recap", bulletPoints: ["Revenue up 18%", "CAC down 9%"], speakerNotes: ["Start with goals", "Explain trends"] },
    version: "1.4.2",
    status: "active",
    trustScore: 93,
    totalCalls: 64800,
    avgLatencyMs: 1320,
    uptimePercent: 99.2,
    rating: 4.8,
    reviewCount: 184,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 120
  },
  {
    id: "mock-audio-transcriber-7",
    name: "WhisperFast Voice2Text",
    description: "Ultra-fast, multilingual audio transcription agent supporting over 50 languages with built-in speaker diarization.",
    creatorId: "mock-user-7",
    creatorUsername: "audio_labs",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-audio-transcriber-7",
    capabilityTags: ["audio", "speech-to-text", "nlp"],
    supportedLanguages: ["python", "go", "rust"],
    latencyMs: 2500,
    costPerCall: 0.30,
    inputSchema: { type: "object", properties: { audioUrl: { type: "string" } } },
    outputSchema: { type: "object", properties: { text: { type: "string" }, speakers: { type: "number" } } },
    exampleInput: { audioUrl: "https://example.com/meeting.mp3" },
    exampleOutput: { text: "Hello everyone, let's start the meeting.", speakers: 2 },
    version: "1.8.2",
    status: "active",
    trustScore: 94,
    totalCalls: 310000,
    avgLatencyMs: 2400,
    uptimePercent: 99.0,
    rating: 4.6,
    reviewCount: 521,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 80
  },
  {
    id: "mock-study-notes-7b",
    name: "Lecture Note Synth",
    description: "Turns study material, class recordings, and slide decks into revision notes, flashcards, and concise summaries for students.",
    creatorId: "mock-user-7b",
    creatorUsername: "study_stack",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-study-notes-7b",
    capabilityTags: ["summarization", "education", "productivity"],
    supportedLanguages: ["python", "node", "typescript"],
    latencyMs: 1700,
    costPerCall: 0.06,
    inputSchema: { type: "object", properties: { contentUrl: { type: "string" }, outputType: { type: "string" } } },
    outputSchema: { type: "object", properties: { notes: { type: "string" }, flashcards: { type: "array" } } },
    exampleInput: { contentUrl: "https://example.com/lecture.pdf", outputType: "flashcards" },
    exampleOutput: { notes: "Neural networks overview", flashcards: ["What is backpropagation?", "Define overfitting"] },
    version: "2.1.0",
    status: "active",
    trustScore: 90,
    totalCalls: 88400,
    avgLatencyMs: 1620,
    uptimePercent: 98.9,
    rating: 4.7,
    reviewCount: 267,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 140
  },
  {
    id: "mock-ui-generator-8",
    name: "React Flow Builder",
    description: "Generates beautiful, responsive React components styled with Tailwind CSS from rough wireframes or text descriptions.",
    creatorId: "mock-user-8",
    creatorUsername: "frontend_wizard",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-ui-generator-8",
    capabilityTags: ["code-generation", "design", "frontend"],
    supportedLanguages: ["typescript", "javascript"],
    latencyMs: 5000,
    costPerCall: 0.40,
    inputSchema: { type: "object", properties: { prompt: { type: "string" } } },
    outputSchema: { type: "object", properties: { code: { type: "string" } } },
    exampleInput: { prompt: "A dark mode login form" },
    exampleOutput: { code: "export const Login = () => <div className='bg-black'>...</div>" },
    version: "4.0.0",
    status: "active",
    trustScore: 91,
    totalCalls: 45000,
    avgLatencyMs: 5100,
    uptimePercent: 97.5,
    rating: 4.7,
    reviewCount: 215,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 40
  },
  {
    id: "mock-ml-evaluator-8b",
    name: "Model Eval Copilot",
    description: "Evaluates classification models, surfaces false positives and false negatives, and generates precision, recall, and confusion-matrix summaries for ML teams.",
    creatorId: "mock-user-8b",
    creatorUsername: "ml_ops_lab",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-ml-evaluator-8b",
    capabilityTags: ["classification", "analytics", "python"],
    supportedLanguages: ["python", "jupyter", "typescript"],
    latencyMs: 1900,
    costPerCall: 0.12,
    inputSchema: { type: "object", properties: { predictionsUrl: { type: "string" }, labelsUrl: { type: "string" } } },
    outputSchema: { type: "object", properties: { precision: { type: "number" }, recall: { type: "number" }, failureModes: { type: "array" } } },
    exampleInput: { predictionsUrl: "https://example.com/preds.csv", labelsUrl: "https://example.com/labels.csv" },
    exampleOutput: { precision: 0.96, recall: 0.91, failureModes: ["marketing emails misclassified as spam"] },
    version: "1.3.4",
    status: "active",
    trustScore: 94,
    totalCalls: 28600,
    avgLatencyMs: 1820,
    uptimePercent: 99.4,
    rating: 4.8,
    reviewCount: 143,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 100
  },
  {
    id: "mock-ml-test-writer-8c",
    name: "Test Forge ML",
    description: "Generates regression tests for preprocessing pipelines, feature engineering, and model-serving code with dataset-aware edge cases.",
    creatorId: "mock-user-8c",
    creatorUsername: "qa_foundry",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-ml-test-writer-8c",
    capabilityTags: ["test-writing", "testing", "python"],
    supportedLanguages: ["python", "typescript", "go"],
    latencyMs: 1600,
    costPerCall: 0.11,
    inputSchema: { type: "object", properties: { repoUrl: { type: "string" }, focusArea: { type: "string" } } },
    outputSchema: { type: "object", properties: { testFiles: { type: "array" }, edgeCases: { type: "array" } } },
    exampleInput: { repoUrl: "https://github.com/user/repo", focusArea: "data preprocessing" },
    exampleOutput: { testFiles: ["tests/test_tokenizer.py"], edgeCases: ["empty subject line", "emoji-heavy message"] },
    version: "2.0.0",
    status: "active",
    trustScore: 92,
    totalCalls: 41800,
    avgLatencyMs: 1510,
    uptimePercent: 99.1,
    rating: 4.7,
    reviewCount: 188,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 120
  },
  {
    id: "mock-bug-triage-8d",
    name: "Issue Triage Radar",
    description: "Clusters bug reports, labels failure modes, and prioritizes noisy issue queues for fast-moving engineering teams.",
    creatorId: "mock-user-8d",
    creatorUsername: "ops_radar",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-bug-triage-8d",
    capabilityTags: ["bug-triage", "classification", "automation"],
    supportedLanguages: ["python", "node", "typescript"],
    latencyMs: 1300,
    costPerCall: 0.07,
    inputSchema: { type: "object", properties: { issues: { type: "array" } } },
    outputSchema: { type: "object", properties: { clusters: { type: "array" }, priorityQueue: { type: "array" } } },
    exampleInput: { issues: ["false positive in filtering", "dataset imbalance issue"] },
    exampleOutput: { clusters: ["model quality", "data drift"], priorityQueue: ["false positive in filtering"] },
    version: "1.7.1",
    status: "active",
    trustScore: 89,
    totalCalls: 63900,
    avgLatencyMs: 1260,
    uptimePercent: 98.8,
    rating: 4.6,
    reviewCount: 209,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 180
  },
  {
    id: "mock-release-notes-8e",
    name: "Release Note Pilot",
    description: "Turns commits, experiments, and issue threads into clean changelogs and progress summaries for product and engineering updates.",
    creatorId: "mock-user-8e",
    creatorUsername: "release_ops",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-release-notes-8e",
    capabilityTags: ["changelog-generation", "summarization", "productivity"],
    supportedLanguages: ["python", "typescript", "node"],
    latencyMs: 980,
    costPerCall: 0.05,
    inputSchema: { type: "object", properties: { commits: { type: "array" }, issues: { type: "array" } } },
    outputSchema: { type: "object", properties: { changelog: { type: "string" }, highlights: { type: "array" } } },
    exampleInput: { commits: ["Improve tokenizer", "Add Naive Bayes model"], issues: ["false positives"] },
    exampleOutput: { changelog: "Improved tokenization and model coverage", highlights: ["Lowered false-positive rate"] },
    version: "3.2.0",
    status: "active",
    trustScore: 90,
    totalCalls: 72400,
    avgLatencyMs: 940,
    uptimePercent: 99.5,
    rating: 4.7,
    reviewCount: 261,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 220
  },
  {
    id: "mock-crypto-sentiment-9",
    name: "Alpha Signal Detector",
    description: "Scrapes Reddit, Twitter, and Discord to determine the real-time social sentiment score of any cryptocurrency.",
    creatorId: "mock-user-9",
    creatorUsername: "defi_degen",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-crypto-sentiment-9",
    capabilityTags: ["finance", "analytics", "data-extraction"],
    supportedLanguages: ["python", "node"],
    latencyMs: 1800,
    costPerCall: 0.08,
    inputSchema: { type: "object", properties: { ticker: { type: "string" } } },
    outputSchema: { type: "object", properties: { sentiment: { type: "string" }, score: { type: "number" } } },
    exampleInput: { ticker: "BTC" },
    exampleOutput: { sentiment: "Bullish", score: 85 },
    version: "1.1.0",
    status: "active",
    trustScore: 78,
    totalCalls: 1200000,
    avgLatencyMs: 1900,
    uptimePercent: 96.0,
    rating: 4.1,
    reviewCount: 88,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 500
  },
  {
    id: "mock-translator-10",
    name: "Polyglot Perfect",
    description: "Context-aware translation agent that preserves cultural nuances, idioms, and formatting across 100+ languages.",
    creatorId: "mock-user-10",
    creatorUsername: "global_lingo",
    endpointUrl: "https://api.agenthub.dev/v1/run/mock-translator-10",
    capabilityTags: ["translation", "nlp", "productivity"],
    supportedLanguages: ["java", "python", "ruby", "c#"],
    latencyMs: 600,
    costPerCall: 0.02,
    inputSchema: { type: "object", properties: { text: { type: "string" }, targetLang: { type: "string" } } },
    outputSchema: { type: "object", properties: { translatedText: { type: "string" } } },
    exampleInput: { text: "It's raining cats and dogs", targetLang: "es" },
    exampleOutput: { translatedText: "Está lloviendo a cántaros" },
    version: "5.2.1",
    status: "active",
    trustScore: 97,
    totalCalls: 3400000,
    avgLatencyMs: 580,
    uptimePercent: 99.9,
    rating: 4.9,
    reviewCount: 1420,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
    rateLimit: 1000
  }
];
