import { collection, addDoc, Timestamp } from "firebase/firestore";
import { db } from "./firebase";
import { Agent } from "./types";

const makeRandomHash = (str: string) => Array.from(str).reduce((s, c) => Math.imul(31, s) + c.charCodeAt(0) | 0, 0);

const getRandomTimestamp = (daysBack: number) => {
  const date = new Date();
  date.setDate(date.getDate() - Math.floor(Math.random() * daysBack));
  return Timestamp.fromDate(date);
};

export const seedMockAgents = async () => {
  const MOCK_AGENTS = [
    {
      name: "PR Review Agent",
      description: "Reviews GitHub pull requests automatically, formatting inline comments and providing a high-level summary of the code quality.",
      creatorId: "user1",
      creatorUsername: "ai-hero",
      endpointUrl: "https://example.com/api/pr-review",
      capabilityTags: ["code-review", "github", "quality"],
      supportedLanguages: ["Python", "JavaScript", "TypeScript"],
      latencyMs: 1400,
      costPerCall: 0.05,
      inputSchema: { type: "object", properties: { pr_url: { type: "string" } } },
      outputSchema: { type: "object", properties: { summary: { type: "string" }, comments: { type: "array" } } },
      exampleInput: { pr_url: "https://github.com/example/repo/pull/1" },
      exampleOutput: { summary: "Looks good!", comments: [] },
      version: "1.2.0",
      status: "active",
      trustScore: 92,
      totalCalls: 45000,
      avgLatencyMs: 1450,
      uptimePercent: 99.9,
      rating: 4.8,
      reviewCount: 312,
    },
    {
      name: "Code Summarizer",
      description: "Summarizes any given code snippet or file into plain English. Great for onboarding junior devs.",
      creatorId: "user2",
      creatorUsername: "devtools-inc",
      endpointUrl: "https://example.com/api/code-summarizer",
      capabilityTags: ["summarization", "documentation"],
      supportedLanguages: ["JavaScript", "Python", "Go", "Rust"],
      latencyMs: 800,
      costPerCall: 0.01,
      inputSchema: { type: "object", properties: { code: { type: "string" } } },
      outputSchema: { type: "object", properties: { summary: { type: "string" } } },
      exampleInput: { code: "function add(a, b) { return a + b; }" },
      exampleOutput: { summary: "This function adds two numbers and returns the result." },
      version: "2.0.1",
      status: "active",
      trustScore: 85,
      totalCalls: 12000,
      avgLatencyMs: 820,
      uptimePercent: 99.5,
      rating: 4.2,
      reviewCount: 89,
    },
    {
      name: "Bug Triager",
      description: "Classifies and prioritizes bug reports using NLP. Routes them to the right team automatically.",
      creatorId: "user3",
      creatorUsername: "qa-ninja",
      endpointUrl: "https://example.com/api/bug-triager",
      capabilityTags: ["classification", "nlp", "support"],
      supportedLanguages: ["Other"],
      latencyMs: 300,
      costPerCall: 0.005,
      inputSchema: { type: "object", properties: { issue_text: { type: "string" } } },
      outputSchema: { type: "object", properties: { priority: { type: "string" }, team: { type: "string" } } },
      exampleInput: { issue_text: "The payment page crashes when I click checkout." },
      exampleOutput: { priority: "High", team: "Payments" },
      version: "1.0.0",
      status: "active",
      trustScore: 78,
      totalCalls: 8500,
      avgLatencyMs: 350,
      uptimePercent: 98.2,
      rating: 3.9,
      reviewCount: 45,
    },
    {
      name: "Test Writer",
      description: "Generates comprehensive unit tests based on function signatures and descriptions.",
      creatorId: "user4",
      creatorUsername: "tdd-master",
      endpointUrl: "https://example.com/api/test-writer",
      capabilityTags: ["code-generation", "testing"],
      supportedLanguages: ["Java", "TypeScript", "Python"],
      latencyMs: 2500,
      costPerCall: 0.08,
      inputSchema: { type: "object", properties: { function_code: { type: "string" } } },
      outputSchema: { type: "object", properties: { test_code: { type: "string" } } },
      exampleInput: { function_code: "def is_even(n): return n % 2 == 0" },
      exampleOutput: { test_code: "def test_is_even(): assert is_even(2) == True" },
      version: "1.1.0",
      status: "active",
      trustScore: 88,
      totalCalls: 32000,
      avgLatencyMs: 2600,
      uptimePercent: 99.0,
      rating: 4.5,
      reviewCount: 210,
    },
    {
      name: "Changelog Generator",
      description: "Ingests Git commit logs and writes well-structured, easy-to-read changelogs.",
      creatorId: "user5",
      creatorUsername: "release-bot",
      endpointUrl: "https://example.com/api/changelog",
      capabilityTags: ["summarization", "git", "writing"],
      supportedLanguages: ["Other"],
      latencyMs: 1200,
      costPerCall: 0.02,
      inputSchema: { type: "object", properties: { commits: { type: "array" } } },
      outputSchema: { type: "object", properties: { changelog: { type: "string" } } },
      exampleInput: { commits: ["fix: memory leak in worker", "feat: add oauth login"] },
      exampleOutput: { changelog: "# Features\n- Added OAuth Login\n# Fixes\n- Fixed memory leak in worker" },
      version: "3.4.2",
      status: "active",
      trustScore: 95,
      totalCalls: 50000,
      avgLatencyMs: 1100,
      uptimePercent: 99.99,
      rating: 4.9,
      reviewCount: 400,
    },
    {
      name: "Email Drafter",
      description: "Drafts highly professional emails simply from bullet points and a target audience.",
      creatorId: "user6",
      creatorUsername: "writer-pro",
      endpointUrl: "https://example.com/api/email-drafter",
      capabilityTags: ["writing", "generation", "business"],
      supportedLanguages: ["Other"],
      latencyMs: 900,
      costPerCall: 0.008,
      inputSchema: { type: "object", properties: { points: { type: "array" }, tone: { type: "string" } } },
      outputSchema: { type: "object", properties: { email: { type: "string" } } },
      exampleInput: { points: ["delay project 2 weeks", "need more testing"], tone: "professional" },
      exampleOutput: { email: "Dear team,\n\nWe need to push the project deadline by two weeks to accommodate extra testing.\n\nBest,\nMe" },
      version: "1.0.1",
      status: "active",
      trustScore: 82,
      totalCalls: 22000,
      avgLatencyMs: 950,
      uptimePercent: 99.1,
      rating: 4.3,
      reviewCount: 156,
    },
    {
      name: "Slack Summarizer",
      description: "Never read a 50-message thread again. Summarizes Slack discussions into action items.",
      creatorId: "user7",
      creatorUsername: "productivity-hacker",
      endpointUrl: "https://example.com/api/slack-summary",
      capabilityTags: ["summarization", "productivity"],
      supportedLanguages: ["Other"],
      latencyMs: 650,
      costPerCall: 0.015,
      inputSchema: { type: "object", properties: { messages: { type: "array" } } },
      outputSchema: { type: "object", properties: { summary: { type: "string" }, actions: { type: "array" } } },
      exampleInput: { messages: ["Alice: We need to upgrade DB", "Bob: I can do it tomorrow"] },
      exampleOutput: { summary: "DB upgrade needed.", actions: ["Bob to upgrade DB tomorrow"] },
      version: "1.0.0",
      status: "active",
      trustScore: 90,
      totalCalls: 18000,
      avgLatencyMs: 680,
      uptimePercent: 99.8,
      rating: 4.7,
      reviewCount: 220,
    },
    {
      name: "Data Extractor",
      description: "Extracts structured JSON data points from messy, unstructured text documents.",
      creatorId: "user8",
      creatorUsername: "data-wizard",
      endpointUrl: "https://example.com/api/extract",
      capabilityTags: ["data-extraction", "parsing"],
      supportedLanguages: ["Python", "Other"],
      latencyMs: 1800,
      costPerCall: 0.04,
      inputSchema: { type: "object", properties: { text: { type: "string" }, fields: { type: "array" } } },
      outputSchema: { type: "object", properties: { extracted: { type: "object" } } },
      exampleInput: { text: "Invoice #1234 from Acme Corp for $500", fields: ["invoice_num", "company", "amount"] },
      exampleOutput: { extracted: { invoice_num: "1234", company: "Acme Corp", amount: 500 } },
      version: "2.5.0",
      status: "active",
      trustScore: 86,
      totalCalls: 25000,
      avgLatencyMs: 1900,
      uptimePercent: 99.2,
      rating: 4.4,
      reviewCount: 165,
    },
    {
      name: "Sentiment Analyzer",
      description: "Detects emotional sentiment in customer feedback. Outputs positive, neutral, or negative.",
      creatorId: "user9",
      creatorUsername: "ml-guru",
      endpointUrl: "https://example.com/api/sentiment",
      capabilityTags: ["sentiment-analysis", "nlp", "classification"],
      supportedLanguages: ["Other"],
      latencyMs: 200,
      costPerCall: 0.002,
      inputSchema: { type: "object", properties: { text: { type: "string" } } },
      outputSchema: { type: "object", properties: { sentiment: { type: "string" }, confidence: { type: "number" } } },
      exampleInput: { text: "I absolutely love this new feature!" },
      exampleOutput: { sentiment: "positive", confidence: 0.98 },
      version: "1.0.5",
      status: "active",
      trustScore: 94,
      totalCalls: 80000,
      avgLatencyMs: 210,
      uptimePercent: 99.7,
      rating: 4.8,
      reviewCount: 520,
    },
    {
      name: "SQL Generator",
      description: "Converts plain English questions into valid SQL queries based on a given database schema.",
      creatorId: "user10",
      creatorUsername: "db-admin",
      endpointUrl: "https://example.com/api/text-to-sql",
      capabilityTags: ["code-generation", "database", "nlp"],
      supportedLanguages: ["Other"],
      latencyMs: 2200,
      costPerCall: 0.06,
      inputSchema: { type: "object", properties: { schema: { type: "string" }, question: { type: "string" } } },
      outputSchema: { type: "object", properties: { query: { type: "string" } } },
      exampleInput: { schema: "users(id, name, age)", question: "find users older than 21" },
      exampleOutput: { query: "SELECT * FROM users WHERE age > 21;" },
      version: "1.3.1",
      status: "active",
      trustScore: 89,
      totalCalls: 31000,
      avgLatencyMs: 2250,
      uptimePercent: 99.4,
      rating: 4.6,
      reviewCount: 280,
    }
  ];

  const agentsCol = collection(db, "agents");

  for (const agent of MOCK_AGENTS) {
    const docRef = await addDoc(agentsCol, {
      ...agent,
      createdAt: getRandomTimestamp(30),
      updatedAt: getRandomTimestamp(5),
    });

    try {
      await fetch("/api/upsert-vector", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          agentId: docRef.id,
          text: agent.name + " " + agent.description + " " + agent.capabilityTags.join(" ")
        })
      });
    } catch (e) {
      console.error("Vector DB seed failed:", e);
    }
  }
};
